#
# 服务器-配置
server:
  # 端口
  port: 10301
#
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://authorization-server/jwk
#
# 日志 配置
#
logging:
  # 日志等级
  level:
    cn.com.xuxiaowei: debug
    # Spring Cloud 中无法使用 logging.level.web: debug
    org.springframework.web: debug
    org.springframework.security: debug
